### ISSUE TITLE
리팩토링하기

### ISSUE THREAD

**Issue by DJDrama** [AnJinHyuck/SpartaBasic#1]
`var randomValue :Int = Random.nextInt(1,100)`

다른 개발자가 보았을 때, Random.nextInt 에서 nextInt는 결국 Int 형을 반환한다를 알고 있게 됩니다. 
즉 randomValue 뒤에 Int를 타입으로 명시적으로 선언할 필요가 없습니다!

1. 물론 타입을 명시적으로 선언하는 것이 좋은 습관이지만, 굳이 작성할 필요가 없을 경우에는 제거해주는 것이 좋습니다!(IntelliJ에서도 회색으로 표시가 될 것입니다.)

2. 추가적으로 nextInt(1, 100)은 1에서 99까지 입니다. 1: inclusive, 100: Exclusive
-> 100을 포함하기 위해서는 nextInt(1, 101)로 하셔야 합니다!

3. if (textView.text == randomTextView.text) 
-> 여기서 text는 CharSequence 입니다. (CharSequence는 equals와 hashCode를 구체적으로 작성해두지 않았기 때문에 의도치 않은 결과가 발생할 수 있어서 아래아 같이 작성하는 습관을 길러보세요~!)
-> text.toString()을 이용하여 해당 CharSequence를 String 타입으로 변환하여 비교하는 것이 좋습니다.

다시 수정하여 푸시해보세요~!

**Comment by AnJinHyuck** [comment]
감사합니다!
